# Generated by Django 4.2.15 on 2024-08-12 11:03

from django.db import migrations

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_superuser(
        username='admin',
        email='admin@example.com',
        password='1'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_userdefined_preview'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
